world-builder/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => 'devise_users' }

  get "campaigns/index"
  root "campaigns#index"

  resources :connections
  resources :user_campaigns
  resources :campaigns
  resources :npcs
  resources :users
  resources :worlds
  resources :tags
  resources :locations

  
  
end

world-builder/app/views/home/_flash.html.erb
<% flash.each do |name, msg|%>
    <div class="alert alert-warning alert-dismissible">
        <button class="close" data-dismiss="alert">
            <i class="glyphicon glyphicon-remove-circle"></i>
        </button>
        <%=content_tag(:div, msg) %>
    </div>
<% end %>

world-builder/app/views/home/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "World Builder", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Start Campaigns", campaigns_path%></li>
        <li><%= link_to "Current Users", users_path%></li>
        <li><%= link_to "World List", worlds_path%></li>
        
        <% if user_signed_in? %>
        
        <li><%= link_to "Log out", destroy_user_session_path,method: :delete %></li>
        <li><%= link_to "Update Profile", edit_user_registration_path%></li>

        <% else %>
        <li><%= link_to "Sign up", new_user_registration_path%></li>
        <li><%= link_to "Log in", new_user_session_path%></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>