world-builder/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => 'devise_users' }

  get "campaigns/index"
  root "campaigns#index"

  resources :connections
  resources :user_campaigns
  resources :campaigns
  resources :npcs
  resources :users
  resources :worlds
  resources :tags
  resources :locations

  
  
end

world-builder/app/models/location.rb
class Location < ActiveRecord::Base
    belongs_to :world
    belongs_to :tag
    has_many :npcs
    has_many :parent_locations, :class_name => 'Connection'
    has_many :child_locations, :class_name => 'Connection'
    
        # setters and getters for tag foreign key
    def tag_name=(name)
        self.tag = Tag.find_or_create_by(name: name)
    end

    def tag_name
        self.tag ? self.tag.name : nil
    end
    
        # setters and getters for world foreign key
    def world_name=(name)
        self.world = World.find_or_create_by(name: name)
    end

    def world_name
        self.world ? self.world.name : nil
    end

end

world-builder/app/controllers/locations_controller.rb
class LocationsController < ApplicationController
    def index
        if params.has_key?(:world) == true
            @wlocations = Location.where(world_id: params[:world].to_i)
            world_id = params[:world]
            @world = World.find(world_id)
            name = @world.name
            @name = name
        end
        
        if params.has_key?(:campaign_id) == true
            campaign_id = params[:campaign_id]
            @campaign = Campaign.find(campaign_id)
            @campaign_id = campaign_id
        end
        
        else
            @locations = Location.all
        
    end
    def show
        @tags = Tag.all
        @countries = Location.where(tag_id: 2)
        @connections = Connection.all
        @regions = Location.where(tag_id: 3)
        @cities = Location.where(tag_id: 4)
        @buildings = Location.where(tag_id: 5)
        @worlds = World.all
        @npcs = Npc.all
        @locations = Location.all
        
        
        @hcountries = Location.where(tag_id: 2, hidden:false)
        @hregions = Location.where(tag_id: 3, hidden:false)
        @hcities = Location.where(tag_id: 4, hidden:false)
        @hbuildings = Location.where(tag_id: 5, hidden:false)
        
        id = params[:id] # retrieve movie ID from URI route
        @location = Location.find(id) # look up movie by unique ID
        # will render app/views/movies/show.html.haml by default
        gm = params[:gm]
        @gm = gm
        
        if params.has_key?(:campaign_id) == true
            campaign_id = params[:campaign_id]
            @campaign = Campaign.find(campaign_id)
            @campaign_id = campaign_id
        end
        
        if @location.tag_id > 1
            @connections.where(:child_location_id => @location.id).each do |connection|
                @parent_location_id = connection.parent_location_id
                @parent_location = Location.find(@parent_location_id)
            end
        end
    end
    
    def new
        @location = Location.new
    # default: render 'new' template
    end 

    def location_params
        params.require(:location).permit(:name,:description,:world_name,:tag_name,:gm_note,:character_note,:hidden)
    end

    def create
        params.require(:location)
        params[:location].permit(:name,:description,:world_id,:tag_id,:campaign_id)
        # shortcut: params.require(:movie).permit(:title,:rating,:release_date)
        # rest of code...
        @location = Location.create!(location_params)
        flash[:notice] = "#{@location.name} was successfully created."
        redirect_to locations_path
    end
    
    def edit
        @location = Location.find params[:id]
        @gm = params[:gm]
        @campaign_id = params[:campaign_id]
    end

    def update
        @location = Location.find params[:id]
        @location.update_attributes!(location_params)
        flash[:notice] = "#{@location.name} was successfully updated."
        redirect_to location_path(@location.id, gm: @gm, campaign_id: @campaign_id)
    end
    
    def destroy
        @location = Location.find(params[:id])
        @location.destroy
        flash[:notice] = "Location '#{@location.name}' deleted."
        redirect_to location_path
    end
end

world-builder/app/views/locations/edit.html.haml
%h2 Edit #{@location.name}

= image_tag "/images/default_location_image.png"

= form_tag location_path(@location), :method => :put do

  = label :location, :name, 'Name'
  = text_field :location, :name

  = label :location, :description, 'Description'
  = text_area :location, :description
 
  = label :location, :gm_note, 'GM Note'
  = text_area :location, :gm_note
  
  = label :location, :world_id, 'Select a World for your Location'
  = collection_select(:location, :world_id,World.all,:name,:name,prompt:true)
  
  = label :location, :hidden, 'check box if location is still unknown (hidden)'
  = check_box :location, :hidden
  
  <br><br>
  = submit_tag 'Save Changes'
= link_to "Back to #{@location.name} Details", location_path(@location.id, gm: @gm, campaign_id: @campaign_id), :class => 'button'

world-builder/app/views/locations/index.html.haml
- if params.has_key?(:world) == false
  = link_to 'Back to campaign list', campaigns_path, :class => 'button'
- if params.has_key?(:world) == true
  - if params.has_key?(:campaign_id) == true
    = link_to "Back to #{@campaign.name}", campaign_path(@campaign_id), :class => 'button'

  %h1 #@name
  
  %p
    = link_to 'Create New location', new_location_path, :class => "button"
  %table#campaigns
    %thead
      %tr
        %th Location Name
        %th Date Created
        %th Edit Location
    %tbody
      - @wlocations.each do |location|
        %tr
          %td= link_to "#{location.name}", location_path(location)
          %td= location.created_at
          %td= link_to "Edit #{location.name}", edit_location_path(location)

- else
  %h1 All Locations
  
  %p
    = link_to 'Create New location', new_location_path, :class => "button"
  %table#campaigns
    %thead
      %tr
        %th Location Name
        %th Date Created
        %th Edit Location
    %tbody
      - @locations.each do |location|
        %tr
          %td= link_to "#{location.name}", location_path(location)
          %td= location.created_at
          %td= link_to "Edit #{location.name}", edit_location_path(location)
  
  

world-builder/app/views/locations/new.html.haml
%h2 Create New Location

= image_tag "/images/default_location_image.png"

= form_tag locations_path, :method => :post do

  = label :location, :world_id, 'Select a World for your Campaign'
  = collection_select(:location, :world_name, World.all, :name, :name, prompt: true)
  
  = label :location, :tag_id, 'Location Type'
  = collection_select(:location, :tag_name, Tag.all, :name, :name, prompt:true)

  = label :location, :name, 'Name'
  = text_field :location, :name

  = label :location, :description, 'Description'
  = text_area :location, :description
 
  = label :location, :gm_note, 'GM Note'
  = text_area :location, :gm_note
  
  = label :location, :hidden, 'check box if location is stil unknown (hidden)'
  = check_box :location, :hidden

  <br><br>
  = submit_tag 'Save Changes'
= link_to 'Back to location list', locations_path, :class => 'button'

world-builder/app/views/locations/show.html.haml
- if params.has_key?(:campaign_id) == true
  - if @location.tag_id == 1
    = link_to "Back to #{@campaign.name}", campaign_path(@campaign_id), :class => 'button'
  - else
    = link_to "Back to #{@parent_location.name}", location_path(@parent_location_id, gm: @gm, campaign_id: @campaign_id), :class => 'button'
- else
  = link_to "Back to Location List", locations_path, :class => 'button'
  = link_to 'Add Connection', new_connection_path(location: @location), :class => "button"

- if current_user.id == @gm.to_i
  %p
    = link_to 'Edit Location Details', edit_location_path(gm: @gm, campaign_id: @campaign_id), :class => "button"

%h2 #{@location.name}

= image_tag "/images/default_location_image.png"

%ul#details
  %li
    Created on:
    = @location.created_at.strftime("%B %d, %Y")

%h4 Description:

%div#description= @location.description

%h4 GM Note:

%div#gm_note= @location.gm_note

%h4 Player Note:

%div#player_note= @location.player_note

- if current_user.id == @gm.to_i
  .left.column
    - if @location.tag_id < 5
      %table#campaigns
        %thead
          %tr
            %th #{@tags = Tag.find(@location.tag_id + 1).name + " List"}
        %tbody
          - if @location.tag_id == 1
            - @connections.where(:parent_location_id => @location.id).each do |connection|
              - @countries.where(:id => connection.child_location_id).each do |country|
                - if country.hidden == true
                  %tr
                    %td= link_to "#{country.name} - (hidden to players)", location_path(country, gm: @gm, campaign_id: @campaign_id)
                - else
                  %tr
                    %td= link_to "#{country.name}", location_path(country, gm: @gm, campaign_id: @campaign_id)
                  
          - if @location.tag_id == 2
            - @connections.where(:parent_location_id => @location.id).each do |connection|
              - @regions.where(:id => connection.child_location_id).each do |region|
                - if region.hidden == true
                  %tr
                    %td= link_to "#{region.name} - (hidden to players)", location_path(region, gm: @gm, campaign_id: @campaign_id)
                - else
                  %tr
                    %td= link_to "#{region.name}", location_path(region, gm: @gm, campaign_id: @campaign_id)
          
          - if @location.tag_id == 3
            - @connections.where(:parent_location_id => @location.id).each do |connection|
              - @cities.where(:id => connection.child_location_id).each do |city|
                - if city.hidden == true
                  %tr
                    %td= link_to "#{city.name} - (hidden to players)", location_path(city, gm: @gm, campaign_id: @campaign_id)
                - else
                  %tr
                    %td= link_to "#{city.name}", location_path(city, gm: @gm, campaign_id: @campaign_id)
                  
          - if @location.tag_id == 4
            - @connections.where(:parent_location_id => @location.id).each do |connection|
              - @buildings.where(:id => connection.child_location_id).each do |building|
                - if building.hidden == true
                  %tr
                    %td= link_to "#{building.name} - (hidden to players)", location_path(building, gm: @gm, campaign_id: @campaign_id)
                - else
                  %tr
                    %td= link_to "#{building.name}", location_path(building, gm: @gm, campaign_id: @campaign_id)

- else
  .left.column
    - if @location.tag_id < 5
      %table#campaigns
        %thead
          %tr
            %th #{@tags = Tag.find(@location.tag_id + 1).name + " List"}
        %tbody
          - if @location.tag_id == 1
            - @connections.where(:parent_location_id => @location.id).each do |connection|
              - @hcountries.where(:id => connection.child_location_id).each do |country|
                %tr
                  %td= link_to "#{country.name}", location_path(country, campaign_id: @campaign_id)
                  
          - if @location.tag_id == 2
            - @connections.where(:parent_location_id => @location.id).each do |connection|
              - @hregions.where(:id => connection.child_location_id).each do |region|
                %tr
                  %td= link_to "#{region.name}", location_path(region, campaign_id: @campaign_id)
          
          - if @location.tag_id == 3
            - @connections.where(:parent_location_id => @location.id).each do |connection|
              - @hcities.where(:id => connection.child_location_id).each do |city|
                %tr
                  %td= link_to "#{city.name}", location_path(city, campaign_id: @campaign_id)
                  
          - if @location.tag_id == 4
            - @connections.where(:parent_location_id => @location.id).each do |connection|
              - @hbuildings.where(:id => connection.child_location_id).each do |building|
                %tr
                  %td= link_to "#{building.name}", location_path(building, campaign_id: @campaign_id)

- if params.has_key?(:campaign_id) == true
  - if current_user.id == @gm.to_i
    .left.column
      %table#campaigns
        %thead
          %tr
            %th NPCs
        %tbody
          -@npcs.where(:location_id => @location.id).each do |npc|
            %tr
              %td= link_to "#{npc.name}", npc_path(npc, gm: @gm, campaign_id: @campaign.id)
      
      %p
        = link_to 'Create New NPC', new_npc_path(gm: @gm, campaign_id: @campaign_id, location_id: @location.id), :class => "button"
      
      
  - else
    .left.column
      %table#campaigns
        %thead
          %tr
            %th NPCs
        %tbody
          -@npcs.where(:location_id => @location.id).each do |npc|
            %tr
              %td= link_to "#{npc.name}", npc_path(npc)
      
- else
  .left.column
    %table#campaigns
      %thead
        %tr
          %th NPCs
      %tbody
        -@npcs.where(:location_id => @location.id).each do |npc|
          %tr
            %td= link_to "#{npc.name}", npc_path(npc)