world-builder/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => 'devise_users' }

  get "campaigns/index"
  root "campaigns#index"

  resources :connections
  resources :user_campaigns
  resources :campaigns
  resources :npcs
  resources :users
  resources :worlds
  resources :tags
  resources :locations

  
  
end

world-builder/app/models/campaign.rb
class Campaign < ActiveRecord::Base
    belongs_to :user
    belongs_to :world
    has_many :user_campaigns
    
    # setters and getters for world foreign key
    def world_name=(name)
        self.world = World.find_or_create_by(name: name)
    end

    def world_name
        self.world ? self.world.name : nil
    end
    
    # setters and getters for user foreign key
    def user_name=(name)
        self.user = User.find_or_create_by(name: name)
    end

    def user_name
        self.user ? self.user.name : nil
    end
end

world-builder/app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
   #before_action :correct_user, only: [:edit, :update, :destroy]
   before_action :authenticate_user!
   
    def index
        @campaigns = Campaign.all
        @user_campaigns = UserCampaign.all
        
        if params.has_key?(:world) == true
            world = params[:world]
            @world = world
        end
        #@userCampaigns = Campaign.where("user_id = User.current_user.id")
    end
    def show
        @users = User.all
        @locations = Location.all
        @continents = Location.where(tag_id: 1)
        @hcontinents = Location.where(tag_id: 1, hidden:false)
        @user_campaigns = UserCampaign.all
        id = params[:id] # retrieve movie ID from URI route
        @campaign = Campaign.find(id) # look up movie by unique ID
        # will render app/views/movies/show.html.haml by default
    end
    
    def new
        @campaign = Campaign.new
    # default: render 'new' template
    end 

    def campaign_params
        params.require(:campaign).permit(:name, :world_name, :user_name)
    end

    def create
        params.require(:campaign)
        params[:campaign].permit(:name, :world_id, :user_name)
        # shortcut: params.require(:movie).permit(:title,:rating,:release_date)
        # rest of code...
        #world = World.find_or_create_by(name: params[:campaign][:world_id])
        @campaign = Campaign.create!(campaign_params)
        flash[:notice] = "#{@campaign.name} was successfully created."
        redirect_to campaigns_path
    end
    
    def edit
        @campaign = Campaign.find params[:id]
    end

    def update
        @campaign = Campaign.find params[:id]
        @campaign.update_attributes!(campaign_params)
        flash[:notice] = "#{@campaign.name} was successfully updated."
        redirect_to campaign_path(@campaign)
    end
    
    def destroy
        @campaign = Campaign.find(params[:id])
        @campaign.destroy
        flash[:notice] = "Campaign '#{@campaign.name}' deleted."
        redirect_to campaign_path
    end
    
    # define the current and correct user 
    def correct_user
        #@mycampaign = current_user.campaigns.find_by(id: params[:id])
        #redirect_to campaigns_path, notice: "Not Authorized to edit this Campaign" if @campaign.nil?
    end
end

world-builder/app/views/campaigns/edit.html.haml
%h2 Edit Campaign

= form_tag campaign_path(@campaign), :method => :put do

    = label :campaign, :name, 'Change the name of your Campaign'
    = text_field :campaign, 'name'
    
    = label :campaign, :world_id, 'Change your campaign world'
    = collection_select(:campaign, :world_name, World.all, :name, :name, prompt: true)
    
    = submit_tag 'Save Changes'
= link_to "Back to #{@campaign.name} details", campaign_path(@campaign.id), :class => 'button'

world-builder/app/views/campaigns/index.html.haml
#content
  .parent
    %p
      = link_to 'Create New Campaign', new_campaign_path, :class => "button"  
    %p
      = link_to 'Create New World', new_world_path, :class => "button"
    %p
      = link_to 'View Tags', tags_path, :class => "button"
    %p
      = link_to 'View Locations', locations_path, :class => "button"
  .right.column
    %table#campaigns
      %thead
        %tr
          %th Your Campaigns
      %tbody
        - @campaigns.where(:user_id => current_user.id).each do |campaign|
          %tr
            %td= link_to "#{campaign.name}", campaign_path(campaign)
            
    

  .left.column
    %table#user_campaigns
      %thead
        %tr
          %th Select a Campaign
          
      %tbody  
        - @user_campaigns.where(:user_id => current_user.id).each do |user_campaign|
          - @campaigns.where(:id => user_campaign.campaign_id).each do |campaign|
            %tr
              %td= link_to "#{@campaign = Campaign.find(user_campaign.campaign_id).name}", campaign_path(campaign)
              %end
    
          
    
    

world-builder/app/views/campaigns/new.html.haml
%h2 Create New Campaign

= form_tag campaigns_path, :method => :post do
    
    = label :campaign, :name, 'Name your Campaign'
    = text_field :campaign, :name
    
    = label :campaign, :world_id, 'Select a World for your Campaign'
    = collection_select(:campaign, :world_name, World.all, :name, :name, prompt: true)
    
    = label :campaign, :user_id, 'Select a GM for your Campaign'
    = collection_select(:campaign, :user_name, User.all, :name, :name, prompt: true)
    
    = submit_tag 'Save Changes'
= link_to 'Back to campaign list', campaigns_path, :class => 'button'

world-builder/app/views/campaigns/show.html.haml
= link_to 'Back to campaign list', campaigns_path, :class => 'button'
= link_to "Edit #{@campaign.name}", edit_campaign_path(@campaign.id), :class => 'button'

%h2 #{@campaign.name}
%ul#details
  %li
    GM:
    = @campaign.user.name
  %li
    Start Date:
    = @campaign.created_at.strftime("%B %d, %Y")
.parent
  %h3 The World of #{@campaign.world.name}
- if current_user.id == @campaign.user_id
  .parent
    %p
      = link_to 'View Locations', locations_path(world: @campaign.world_id, campaign_id: @campaign.id), :class => "button"

- if current_user.id == @campaign.user_id
  .right.column
    %table#campaigns
      %thead
        %tr
          %th Active Players
      %body
        - @user_campaigns.where(:campaign_id => @campaign.id).each do |user_campaign|
          - @users.where(:id => user_campaign.user_id).each do |user|
            - if user.id == @campaign.user_id
              %tr
                %td #{user.name} - (GM)
            - else
              %tr
                %td #{user.name}
    .parent
      = link_to 'Add Player', new_user_campaign_path(campaign_id: @campaign), :class => "button"
- else
  .right.column
    %table#campaigns
      %thead
        %tr
          %th Active Players
      %body
        - @user_campaigns.where(:campaign_id => @campaign.id).each do |user_campaign|
          - @users.where(:id => user_campaign.user_id).each do |user|
            - if user.id == @campaign.user_id
              %tr
                %td #{user.name} - (GM)
            - else
              %tr
                %td #{user.name}

- if current_user.id == @campaign.user_id
  .left.column
    %table#campaigns
      %thead
        %tr
          %th Continents
      %tbody
        - @continents.where(:world_id => @campaign.world_id).each do |continent|
          -if continent.hidden == true
            %tr
              %td= link_to "#{continent.name} - (hidden to players)", location_path(continent, gm: @campaign.user_id, campaign_id: @campaign.id)
          - else
            %tr
              %td= link_to "#{continent.name}", location_path(continent, gm: @campaign.user_id, campaign_id: @campaign.id)

- else 
  .left.column
    %table#campaigns
      %thead
        %tr
          %th Continents
      %tbody
        - @hcontinents.where(:world_id => @campaign.world_id).each do |continent|
          %tr
            %td= link_to "#{continent.name}", location_path(continent, gm: @campaign.user_id, campaign_id: @campaign.id)