world-builder/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => 'devise_users' }

  get "campaigns/index"
  root "campaigns#index"

  resources :connections
  resources :user_campaigns
  resources :campaigns
  resources :npcs
  resources :users
  resources :worlds
  resources :tags
  resources :locations

  
  
end

world-builder/app/models/world.rb
class World < ActiveRecord::Base
    has_many :campaigns
    has_many :locations
end

world-builder/app/controllers/worlds_controller.rb
class WorldsController < ApplicationController
    before_action :authenticate_user!

    def index
        @worlds = World.all
    end
    def show
        @locations = Location.all
        
        id = params[:id] # retrieve movie ID from URI route
        @world = World.find(id) # look up movie by unique ID
        # will render app/views/movies/show.html.haml by default
    end
    
    def new
        @world = World.new
    # default: render 'new' template
    end 

    def world_params
        params.require(:world).permit(:name,:description,:gm_note,:character_note)
    end

    def create
        params.require(:world)
        params[:world].permit(:name,:description,:gm_note,:character_note)
        # shortcut: params.require(:movie).permit(:title,:rating,:release_date)
        # rest of code...
        @world = World.create!(world_params)
        flash[:notice] = "#{@world.name} was successfully created."
        redirect_to worlds_path
    end
    
    def edit
        @world = World.find params[:id]
    end

    def update
        @world = World.find params[:id]
        @world.update_attributes!(world_params)
        flash[:notice] = "#{@world.name} was successfully updated."
        redirect_to world_path(@world)
    end
    
    def destroy
        @world = World.find(params[:id])
        @world.destroy
        flash[:notice] = "World '#{@world.name}' deleted."
        redirect_to world_path
    end
end

world-builder/app/views/worlds/edit.html.haml
%h2 Edit World

= form_tag world_path(@world), :method => :put do

  = label :world, :name, 'Name'
  = text_field :world, :name

  = label :world, :description, 'Description'
  = text_area :world, :description
 
  = label :world, :gm_note, 'GM Note'
  = text_area :world, :gm_note
  
  = label :world, :character_note, 'Character Note'
  = text_area :world, :character_note
  
  = submit_tag 'Save Changes'
= link_to 'Back to campaign list', :class => 'button'

world-builder/app/views/worlds/index.html.haml
= link_to 'Back to campaign list', campaigns_path, :class => 'button'
%h1 All Worlds

%table#worlds
  %thead
    %tr
      %th World Name
      %th Date Created
      %th Edit World
  %tbody
    - @worlds.each do |world|
      %tr
        %td= link_to "#{world.name}", world_path(world)
        %td= world.created_at
        %td= link_to "Edit #{world.name}", edit_world_path(world)

world-builder/app/views/worlds/new.html.haml
%h2 Create New World

= form_tag worlds_path, :method => :post do

  = label :world, :name, 'Name'
  = text_field :world, :name

  = label :world, :description, 'Description'
  = text_area :world, :description
 
  = label :world, :gm_note, 'GM Note'
  = text_area :world, :gm_note
  
  = submit_tag 'Save Changes'
= link_to 'Back to campaign list', campaigns_path, :class => 'button'

world-builder/app/views/worlds/show.html.haml
= link_to 'Back to world list', worlds_path, :class => 'button'
%h2 Details about #{@world.name}

%ul#details
  %li
    Name:
    = @world.name
  %li
    Created on:
    = @world.created_at.strftime("%B %d, %Y")

%h3 Description:

%div#description= @world.description

%h4 GM Note:

%div#gm_note= @world.gm_note

%h5 Character Note:

%div#character_note= @world.character_note

.left.column
  %table#campaigns
    %thead
      %tr
        %th All Locations in #{@world.name}
    %tbody
      -@locations.where(:world_id => @world.id).each do |location|
        %tr
          %td= link_to "#{location.name}", location_path(location) 